---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: ELTestCBTargetGroup

description: Test for Inheritance

conditions:
  allOf:
    - property:
        name: name
        operator: in-array
        operands:
            - Elliott
